import { useState } from "react";
import Head from 'next/head'
import tw, { styled } from 'twin.macro'
import Menu from '../components/Menu'
import Header from "./Header";
import useMousePosition from '../hooks/useMousePosition'
import { shows } from "../data/shows";

const StyledDesktopOnlyWarning = tw.div`w-screen h-screen justify-center items-center overflow-hidden flex xl:hidden`

const Container = tw.div`w-screen h-screen justify-center items-center overflow-hidden hidden xl:flex`

const Title = tw.h1`text-4xl font-semibold max-w-2xl text-center leading-normal text-gray-800`

const Layout = ({ children }) => {

    const [menuOpen, setMenuOpen] = useState(false);

    const {x, y} = useMousePosition();

    return (
        <>
            <StyledDesktopOnlyWarning>
                <Title>This was just a quick experiment and I did not add tablet/mobile styling.<br/> Please visit on desktop 😘</Title>
            </StyledDesktopOnlyWarning>
            <Container>
                <Head>
                <title>What's On</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://fav.farm/📺" />
                </Head>

                <Header menuOpen={menuOpen} setMenuOpen={setMenuOpen}/>

                <Menu shows={shows} menuOpen={menuOpen} setMenuOpen={setMenuOpen} x={x} y={y}/>

                {children}
            </Container>
        </>
    );
}

export default Layout;
