import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import tw, { styled } from 'twin.macro'
import Header from '../components/Header'
import Menu from '../components/Menu'
import useMousePosition from '../hooks/useMousePosition'

const StyledDesktopOnlyWarning = tw.div`w-screen h-screen justify-center items-center overflow-hidden flex xl:hidden`

const Container = tw.div`w-screen h-screen justify-center items-center overflow-hidden hidden xl:flex`

const Main = tw.div`flex`

const Title = tw.h1`text-4xl font-semibold max-w-2xl text-center leading-normal text-gray-800`

export default function Home({ shows }) {
  const [menuOpen, setMenuOpen] = useState(false);

  const {x, y} = useMousePosition();

  return (
    <>
      <StyledDesktopOnlyWarning>
        <Title>This was just a quick experiment and I did not add tablet/mobile styling.<br/> Please visit on desktop 😘</Title>
      </StyledDesktopOnlyWarning>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header menuOpen={menuOpen} setMenuOpen={setMenuOpen}/>

        <Main>
          <Title>Click on the menu button</Title>
        </Main>
        <Menu shows={shows} menuOpen={menuOpen} setMenuOpen={setMenuOpen} x={x} y={y}/>
      </Container>

    </>
  )
}

export async function getStaticProps(context) {
  const res = await fetch('http://localhost:3000/api/shows/');
  const shows = await res.json()

  if (!shows) {
      return {
          notFound: true
      }
  }

  return {
      props: { shows }
  }
}
